- ros_topic_name: "/keyboard/keypress"
  gz_topic_name: "/keyboard/keypress"
  ros_type_name: "std_msgs/msg/Int32"
  gz_type_name: "gz.msgs.Int32"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ